python train.py \
    --name genimage_detection_resnet \
    --wang2020_data_path=/root/autodl-tmp/AIGC_data/GenImage \
    --data_mode=multi_wang2020 \
    --arch=Imagenet:resnet18 \
    --fix_backbone \
    --batch_size=64 \
    --lr=0.001 \
    --optim=adam \
    --niter=1 \
    --gpu_ids='2' \
    --lora_rank=8 \
    --lora_alpha=1 